# fly.toml app configuration file generated for fishmlserv423 on 2024-08-30T15:54:29+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fishmlserv42'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
