[project]
name = "fishmlserv"
version = "0.1.0"
description = "Serving Machine Learning Model - Using KNN"
authors = [
    {name = "Mingk42", email = "xoals123456t@gmail.com"},
]
dependencies = [
    "fastapi[standard]>=0.112.2",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
